// 03/10: fullscreen creation, mobile plan stacking, closing sheet, entitled GO,
// Coral identity across the four platforms and COM's owner-only history.
// All users, positions, maps, RPCs and SSO responses are mocked. No production writes.
import fs from 'node:fs';import {launch,page,ok} from './harness.mjs';
const onlyIdentity=process.argv.includes('--identity');const out=process.argv[2] || '/tmp';fs.mkdirSync(out,{recursive:true});const browser=await launch();
const now=Date.now(),origin='https://www.totehm.space';
const habit={name:'Run the hill',freq:'every_morning',ints:['love','fight'],step:{t:'Run the hill',f:'every_morning',is:['love','fight']},objectives:[{text:'Move with friends'}],repulsions:[]};
const make=(id,extra={})=>({id,habit:habit.name,freq:habit.freq,intentions:habit.ints,visibility:'shared',location:'on',mode:'social',creator:'nia',mine:false,city:'Lisbon',starts_at:new Date(now-1000).toISOString(),ends_at:new Date(now+3600000).toISOString(),duration_min:60,video:null,exact:null,...extra});
const on=make('on'),off=make('off',{location:'off'}),own=make('own',{mine:true,visibility:'private',exact:{lat:38.7223,lng:-9.1393,place:'My place'}});
const rect=(pg,id)=>pg.$eval('#'+id,e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};});
const state=pg=>pg.evaluate(()=>window.__totehm_space());
const tapPaper=async pg=>{const r=await rect(pg,'totehm-paper');await pg.mouse.click(r.x+r.w/2,r.y+r.h/2);};
async function swipe(pg,x,y,dx,dy){const c=await pg.context().newCDPSession(pg);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let k=1;k<=10;k++){await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*k/10,y:y+dy*k/10}]});await pg.waitForTimeout(15);}await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await c.detach();await pg.waitForTimeout(400);}
const coral=async(pg,sel)=>pg.$eval(sel,e=>{const s=getComputedStyle(e);return s.color==='rgb(251, 213, 202)' && s.fontFamily.includes('Quantico');});
try{
 if(!onlyIdentity){
 {let entitled=false;const maps=[];const {pg,log}=await page(browser,{dir:'space',origin,hasTouch:true,tables:{profiles:[{pseudo:'my_higher_self'}]},rpc:{spot_rules:{clip_seconds:2,duration_min:5,duration_max:720,video_provider:'storage'},space_habits:{ok:true,habits:[habit]},space_discover:b=>({spots:b.p_view==='radar'?[own]:b.p_view==='feed'?[on,off]:[],more:false}),spot_get:b=>({ok:true,spot:b.p_id==='on'?{...on,exact:entitled?{lat:38.724,lng:-9.144}:null}:own})},network:async(url)=>{if(url.host==='www.google.com'){maps.push(url.href);return {status:200,contentType:'text/html',body:'<body>Mock map</body>'};}return null;}});
 await pg.goto(origin+'/');await pg.waitForFunction(()=>window.__totehm_space?.().signed_in);await pg.waitForTimeout(600);
 let s=await state(pg),joy=await rect(pg,'joy'),paper=await rect(pg,'totehm-paper');
 ok(paper.w===110 && joy.y-(s.radar.cy+s.radar.radius)<48,'mobile landing has a larger paper and radar close to joystick');
 ok(await coral(pg,'#member-txt') && await coral(pg,'#tp-name'),'SPACE member and paper name are Quantico Coral');
 ok(!await pg.isVisible('#member i'),'SPACE member status dot is absent');
 const cmp=await rect(pg,'cmp'),tools=await rect(pg,'map-tools');ok(cmp.x+cmp.w/2<s.radar.cx && tools.x+tools.w/2>s.radar.cx && cmp.y<s.radar.cy+s.radar.radius && tools.y<s.radar.cy+s.radar.radius,'compass and zoom occupy opposite radar corners');
 await pg.screenshot({path:out+'/spaces_landing_mobile.png'});
 await pg.click('#cur-h');await pg.waitForSelector('[data-plan-h]');await pg.click('[data-plan-h]');await pg.click('[data-pvis="private"]');
 ok(await pg.isVisible('#p-date') && (await state(pg)).view==='plan','mobile future form receives real clicks above radar');
 await pg.$eval('#v-plan',e=>e.scrollTop=e.scrollHeight);let r=await rect(pg,'v-plan');await swipe(pg,r.x+5,r.y+r.h-25,0,-100);ok((await state(pg)).view==='plan','scrolling future form at its boundary never changes view');
 await pg.click('[data-plan-place]');await pg.waitForTimeout(350);ok((await state(pg)).radar.pin && await pg.isVisible('#radar-map'),'future place picker opens within radar');await pg.click('#place-cancel');await pg.keyboard.press('Escape');await pg.waitForTimeout(700);
 s=await state(pg);await pg.mouse.click(s.radar.cx,s.radar.cy);await pg.waitForFunction(()=>window.__totehm_space().detail);await pg.waitForTimeout(400);
 ok(await pg.locator('#detail .sheet-grab span').isVisible() && await pg.$eval('#joy-box',e=>e.disabled),'detail exposes a drag handle and mutes joystick');
 await pg.keyboard.press('ArrowRight');ok((await state(pg)).view==='radar','arrows do not navigate behind an open detail');
 r=await rect(pg,'detail');await swipe(pg,195,r.y+16,0,Math.min(130,820-r.y-16));ok(!(await state(pg)).detail && !await pg.$eval('#joy-box',e=>e.disabled),'downward handle swipe closes and restores joystick');
 await pg.click('#cur-b');await pg.waitForFunction(()=>window.__totehm_space().rec.step==='ready');await pg.waitForTimeout(1200);ok((await state(pg)).rec.step==='ready' && /Share a space to your Totehm/.test(await pg.textContent('#cam-body')),'camera waits for an explicit start with the requested prompt');
 await pg.click('#joy-box');await pg.waitForFunction(()=>window.__totehm_space().rec.step==='habit');
 for(const viewport of [{width:390,height:844},{width:360,height:640},{width:1440,height:900}]){await pg.setViewportSize(viewport);r=await rect(pg,'cam-body');ok(r.x===0 && r.y===0 && r.w===viewport.width && r.h===viewport.height,'post-video form fills '+viewport.width+' × '+viewport.height);}
 await pg.setViewportSize({width:390,height:844});await pg.click('[data-h="0"]');await pg.click('[data-vis="private"]');ok((await pg.textContent('#cam-body')).includes('DURATION') && !(await pg.textContent('#cam-body')).includes('For how long'),'creation says DURATION');
 await pg.$eval('#cam-body',e=>e.scrollTop=e.scrollHeight);await swipe(pg,375,680,0,-140);ok((await state(pg)).view==='cam' && (await state(pg)).rec.step==='form','post-video boundary swipe keeps the recording and form');
 await pg.screenshot({path:out+'/spaces_recording_form.png'});await pg.click('[data-cancel]');await pg.click('#cur-g');await pg.waitForSelector('[data-go="on"]');
 ok(await pg.locator('[data-go]').count()===1 && await pg.$eval('#feed .habit',e=>getComputedStyle(e).boxShadow!=='none'),'city feed has GO only for ON and shadowed Habit Boxes');
 ok(!await pg.isVisible('#member') && !await pg.isVisible('#tp-hint') && (await rect(pg,'totehm-paper')).w===58,'side view keeps reduced paper without member or instruction');
 await tapPaper(pg);await pg.waitForSelector('[data-filter-h]');ok(await pg.locator('[data-filter-h]').count()===1,'reduced side paper opens the same Habit selector');await pg.click('[data-picker-close]');
 await pg.click('[data-go="on"]');await pg.waitForFunction(()=>window.__totehm_space().detail);ok(maps.length===0 && /subscribers/.test(await pg.textContent('#detail')) && await pg.locator('#detail a[href*="google"]').count()===0,'GO without entitlement shows explanation and no exact map');await pg.locator('#detail [data-close]').last().click();
 entitled=true;await pg.click('[data-go="on"]');await pg.waitForURL('**google.com/maps/dir/**');ok(maps.length===1 && maps[0].includes('destination=38.724%2C-9.144') && log.rpc.filter(x=>x.name==='spot_get').length>=2,'GO resolves current rights then navigates to authorized exact place');
 ok(!log.errors.some(x=>x.startsWith('pageerror')),'SPACE sheets and GO have no JavaScript page error');await pg.context().close();
 }
 // COM history: private/live, past and planned spaces; cursor and cross-domain SSO.
 {const rows=[{id:'private-live',habit:'Run',visibility:'private',starts_at:new Date(now-1000).toISOString(),ends_at:new Date(now+60000).toISOString(),place:'Own private place'},{id:'planned',habit:'Walk',visibility:'shared',starts_at:new Date(now+86400000).toISOString(),ends_at:new Date(now+86403000).toISOString(),city:'Lisbon'}],more={id:'past',habit:'Swim',visibility:'private',starts_at:new Date(now-86400000).toISOString(),ends_at:new Date(now-86340000).toISOString(),place:'My old place'};
 const {pg,log}=await page(browser,{dir:'com',origin:'https://www.totehm.com',tables:{profiles:[{pseudo:'my_higher_self'}]},rpc:{my_spaces:b=>({ok:true,spaces:b.p_before?[more]:rows,more:!b.p_before})},functions:{'sso-mint':{code:'TEST-COM-SPACE'}},network:async(url)=>url.host==='www.totehm.space'?{status:200,contentType:'text/html',body:'<body>Mock SPACE</body>'}:null});
 await pg.goto('https://www.totehm.com/totehm');await pg.waitForSelector('body.member');await pg.click('#conn-bar');await pg.click('#myspaces-open');await pg.waitForSelector('[data-space]');
 ok(await pg.locator('[data-space]').count()===2 && /PRIVATE/.test(await pg.textContent('#myspaces-list')) && /I WILL BE HERE/.test(await pg.textContent('#myspaces-list')),'COM My spaces retrieves private and planned spaces');await pg.click('#myspaces-more');await pg.waitForFunction(()=>document.querySelectorAll('[data-space]').length===3);ok(/I WAS THERE/.test(await pg.textContent('#myspaces-list')) && log.rpc.filter(x=>x.name==='my_spaces')[1].body.p_before_id==='planned','COM history paginates with stable cursor');
 ok(await coral(pg,'#myspaces-name'),'COM history shows actual Totehm name in Coral');await pg.screenshot({path:out+'/com_my_spaces.png'});await pg.keyboard.press('Escape');ok(!await pg.isVisible('#myspaces') && await pg.isVisible('#member-window'),'history Escape returns to member menu');
 await pg.click('#myspaces-open');await pg.waitForSelector('[data-space]');await pg.click('[data-space="private-live"]');await pg.waitForURL('**totehm.space/**');ok(pg.url().includes('spot=private-live') && pg.url().includes('#sso=TEST-COM-SPACE'),'opening a space keeps member authentication via SSO');ok(!log.errors.some(x=>x.startsWith('pageerror')),'COM history has no JavaScript page error');await pg.context().close();
 }
 }
 const pages=[['club','/','member-txt'],['club','/market','member-txt'],['club','/get_higher','conn-bar'],['club','/stoner','conn-bar'],['boutique','/','conn-bar'],['boutique','/streetwear','conn-txt'],['boutique','/totehm','conn-bar'],['com','/console','member-txt'],['com','/creator','member-txt']];
 for(const [dir,path,identity] of pages){const host=dir==='club'?'www.figher.club':dir==='boutique'?'higher.boutique':'www.totehm.com';const {pg,log}=await page(browser,{dir,origin:'https://'+host,tables:{profiles:[{pseudo:'my_higher_self'}]},rpc:{figher_access:{signed_in:true,pseudo:'my_higher_self',thp:false,habit:true},my_collection:{pseudo:'my_higher_self',owned:[],listed:[]},market_view:{works:[],listings:[]},my_console:{signed_in:true,pseudo:'my_higher_self',offer:{},fans:{list:[]},subscriptions:[]}},functions:{'stoner-gate':{access:false},'higher-checkout':{amount:1700,currency:'usd',left:770000}}});await pg.goto('https://'+host+path);await pg.waitForTimeout(700);ok((await pg.textContent('#'+identity)).trim()==='my_higher_self' && await coral(pg,'#'+identity),dir+path+' uses actual Totehm name in Quantico Coral');ok(await pg.locator('#t').count()===0 && !await pg.isVisible('#conn-bar .dot').catch(()=>false) && !await pg.isVisible('#member>i').catch(()=>false),dir+path+' has no centered static T or member dot');ok(!log.errors.some(x=>x.startsWith('pageerror')),dir+path+' identity has no JavaScript page error');await pg.context().close();}
}finally{await browser.close();}
