-- ⚠️ RÉTRO-COPIE · 08/10/2026 — appliquée en base le 06/10/2026 (17:04 UTC) depuis le
-- terminal de Wah (Claude Code), sans fichier dans le dépôt. Texte recopié TEL QUEL
-- de `supabase_migrations.schema_migrations` : NE PAS RÉAPPLIQUER.

create table if not exists public.streetwear_events (
  id bigint generated by default as identity primary key,
  payload jsonb not null,
  state text not null default 'queued' check(state in ('queued','done')),
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  last_error text,
  created_at timestamptz not null default now()
);
alter table public.streetwear_events enable row level security;
revoke all on public.streetwear_events from public,anon,authenticated;
grant all on public.streetwear_events to service_role;
grant usage,select on sequence public.streetwear_events_id_seq to service_role;
create index streetwear_events_due on public.streetwear_events(next_attempt_at) where state='queued';

create or replace function public.streetwear_sync_catalog(p_product jsonb)
returns public.totehm_cloth_support language sql security invoker set search_path = '' as $$
  insert into public.totehm_cloth_support(printful_product_id,printful_variant_map,title,details,print_area,
    avg_fulfillment_days,storage_folder,image_url,price,max_pieces,active,claimed,position)
  values((p_product->>'printful_product_id')::bigint,p_product->'printful_variant_map',p_product->>'title',
    p_product->>'details',p_product->'print_area',(p_product->>'avg_fulfillment_days')::integer,
    p_product->>'storage_folder',p_product->>'image_url',0,0,false,0,0)
  on conflict(printful_product_id) do update set
    printful_variant_map=excluded.printful_variant_map,title=excluded.title,details=excluded.details,
    print_area=excluded.print_area,avg_fulfillment_days=excluded.avg_fulfillment_days,
    storage_folder=coalesce(public.totehm_cloth_support.storage_folder,excluded.storage_folder),
    image_url=coalesce(public.totehm_cloth_support.image_url,excluded.image_url)
  returning *;
$$;

create or replace function public.streetwear_recover_stalled()
returns integer language plpgsql security invoker set search_path = '' as $$
declare j public.streetwear_jobs; recovered integer:=0; ambiguous boolean;
begin
  for j in select * from public.streetwear_jobs where state='running' and updated_at<now()-interval '15 minutes'
    for update skip locked loop
    ambiguous := (j.stage='generation' and coalesce((j.data->>'image_request_started')::boolean,false))
      or (j.stage='curation' and coalesce((j.data->>'prediction_request_started')::boolean,false)
          and j.data->>'prediction_id' is null and j.data->>'upscaled_url' is null);
    update public.streetwear_jobs set state=case when ambiguous then 'error' else 'waiting' end,
      last_error=case when ambiguous then 'provider_outcome_unknown' else 'execution_interrupted' end,
      next_attempt_at=now(),updated_at=now() where cloth_id=j.cloth_id and stage=j.stage;
    if j.stage='generation' then
      update public.totehm_clothes set status=case when ambiguous then 'error_locked' else 'paid' end,
        pipeline_error=case when ambiguous then 'provider_outcome_unknown' else 'execution_interrupted' end where id=j.cloth_id;
    elsif ambiguous then
      update public.totehm_clothes set status='error_locked',pipeline_error='provider_outcome_unknown' where id=j.cloth_id;
    end if;
    recovered:=recovered+1;
  end loop;
  return recovered;
end $$;
revoke all on function public.streetwear_sync_catalog(jsonb),public.streetwear_recover_stalled() from public,anon,authenticated;
grant execute on function public.streetwear_sync_catalog(jsonb),public.streetwear_recover_stalled() to service_role;
